from enum import Enum
from typing import List
from datetime import datetime
from dataclasses import field
from .sf_dataclasses import salesforce_api_dataclass


class JobTypeEnum(str, Enum):
    V2Ingest = "V2Ingest"
    V2Query = "V2Query"
    Classic = "Classic"
    BigObjectIngest = "BigObjectIngest"


class ContentTypeHeaderEnum(str, Enum):
    CSV = 'text/csv'
    JSON = 'application/json'
    XML = 'application/xml'


class ColumnDelimiterEnum(str, Enum):
    BACKQUOTE = "BACKQUOTE"
    CARET = "CARET"
    COMMA = "COMMA"
    PIPE = "PIPE"
    SEMICOLON = "SEMICOLON"
    TAB = "TAB"


class LineEndingEnum(str, Enum):
    CRLF = 'CRLF'
    LF = 'LF'

    
class OperationEnum(str, Enum):
    insert = 'insert'
    upsert = 'upsert'
    update = 'update'
    delete = 'delete'
    hardDelete = 'hardDelete'
    query = 'query'
    queryAll = 'queryAll'

    
class JobStateEnum(str, Enum):
    Open = 'Open'
    Closed = 'Closed'
    Aborted = 'Aborted'
    Failed = 'Failed'
    UploadComplete = 'UploadComplete'

    
class BatchStateEnum(str, Enum):
    Queued = 'Queued'
    InProgress = 'InProgress'
    Completed = 'Completed'
    Failed = 'Failed'
    NotProcessed = 'NotProcessed'

    
class ConcurrencyModeEnum(str, Enum):
    Parallel = 'Parallel'
    Serial = 'Serial'

    
class ContentType(str, Enum):
    XML = 'XML'
    CSV = 'CSV'
    ZIP_XML = 'ZIP_XML'
    ZIP_CSV = 'ZIP_CSV'
    JSON = 'JSON'

    
class StatusCode(str, Enum):
    ALL_OR_NONE_OPERATION_ROLLED_BACK = 'ALL_OR_NONE_OPERATION_ROLLED_BACK'
    ALREADY_APPLIED = 'ALREADY_APPLIED'
    ALREADY_IN_PROCESS = 'ALREADY_IN_PROCESS'
    ALREADY_REDEEMED_VOUCHER = 'ALREADY_REDEEMED_VOUCHER'
    APEX_DATA_ACCESS_RESTRICTION = 'APEX_DATA_ACCESS_RESTRICTION'
    APEX_FAILED = 'APEX_FAILED'
    ASSIGNEE_TYPE_REQUIRED = 'ASSIGNEE_TYPE_REQUIRED'
    ATTRIBUTE_DEFINITION_LIMIT_EXCEEDED = 'ATTRIBUTE_DEFINITION_LIMIT_EXCEEDED'
    AURA_COMPILE_ERROR = 'AURA_COMPILE_ERROR'
    AUTH_PROVIDER_NEEDS_AUTH = 'AUTH_PROVIDER_NEEDS_AUTH'
    AUTH_PROVIDER_NOT_FOUND = 'AUTH_PROVIDER_NOT_FOUND'
    B2B_SEARCH_ADMIN_ERROR = 'B2B_SEARCH_ADMIN_ERROR'
    BAD_CUSTOM_ENTITY_PARENT_DOMAIN = 'BAD_CUSTOM_ENTITY_PARENT_DOMAIN'
    BCC_NOT_ALLOWED_IF_BCC_COMPLIANCE_ENABLED = 'BCC_NOT_ALLOWED_IF_BCC_COMPLIANCE_ENABLED'
    BLOCKED_EXCLUSIVE = 'BLOCKED_EXCLUSIVE'
    CANNOT_CASCADE_PRODUCT_ACTIVE = 'CANNOT_CASCADE_PRODUCT_ACTIVE'
    CANNOT_CHANGE_FIELD_TYPE_OF_APEX_REFERENCED_FIELD = 'CANNOT_CHANGE_FIELD_TYPE_OF_APEX_REFERENCED_FIELD'
    CANNOT_CHANGE_FIELD_TYPE_OF_REFERENCED_FIELD = 'CANNOT_CHANGE_FIELD_TYPE_OF_REFERENCED_FIELD'
    CANNOT_CREATE_ANOTHER_MANAGED_PACKAGE = 'CANNOT_CREATE_ANOTHER_MANAGED_PACKAGE'
    CANNOT_DEACTIVATE_DIVISION = 'CANNOT_DEACTIVATE_DIVISION'
    CANNOT_DELETE_GLOBAL_ACTION_LIST = 'CANNOT_DELETE_GLOBAL_ACTION_LIST'
    CANNOT_DELETE_LAST_DATED_CONVERSION_RATE = 'CANNOT_DELETE_LAST_DATED_CONVERSION_RATE'
    CANNOT_DELETE_MANAGED_OBJECT = 'CANNOT_DELETE_MANAGED_OBJECT'
    CANNOT_DISABLE_LAST_ADMIN = 'CANNOT_DISABLE_LAST_ADMIN'
    CANNOT_ENABLE_IP_RESTRICT_REQUESTS = 'CANNOT_ENABLE_IP_RESTRICT_REQUESTS'
    CANNOT_EXECUTE_FLOW_TRIGGER = 'CANNOT_EXECUTE_FLOW_TRIGGER'
    CANNOT_FREEZE_SELF = 'CANNOT_FREEZE_SELF'
    CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY = 'CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY'
    CANNOT_MODIFY_MANAGED_OBJECT = 'CANNOT_MODIFY_MANAGED_OBJECT'
    CANNOT_PASSWORD_LOCKOUT = 'CANNOT_PASSWORD_LOCKOUT'
    CANNOT_POST_TO_ARCHIVED_GROUP = 'CANNOT_POST_TO_ARCHIVED_GROUP'
    CANNOT_RENAME_APEX_REFERENCED_FIELD = 'CANNOT_RENAME_APEX_REFERENCED_FIELD'
    CANNOT_RENAME_APEX_REFERENCED_OBJECT = 'CANNOT_RENAME_APEX_REFERENCED_OBJECT'
    CANNOT_RENAME_REFERENCED_FIELD = 'CANNOT_RENAME_REFERENCED_FIELD'
    CANNOT_RENAME_REFERENCED_OBJECT = 'CANNOT_RENAME_REFERENCED_OBJECT'
    CANNOT_REPARENT_RECORD = 'CANNOT_REPARENT_RECORD'
    CANNOT_UPDATE_CONVERTED_LEAD = 'CANNOT_UPDATE_CONVERTED_LEAD'
    CANT_DISABLE_CORP_CURRENCY = 'CANT_DISABLE_CORP_CURRENCY'
    CANT_UNSET_CORP_CURRENCY = 'CANT_UNSET_CORP_CURRENCY'
    CART_NOT_FOUND = 'CART_NOT_FOUND'
    CHECKOUT_CONFLICT = 'CHECKOUT_CONFLICT'
    CHECKOUT_EXPIRED = 'CHECKOUT_EXPIRED'
    CHECKOUT_INVALIDATED = 'CHECKOUT_INVALIDATED'
    CHECKOUT_LOCKED = 'CHECKOUT_LOCKED'
    CHECKOUT_NOT_FOUND = 'CHECKOUT_NOT_FOUND'
    CHECKOUT_UNAUTHORIZED = 'CHECKOUT_UNAUTHORIZED'
    CHILD_SHARE_FAILS_PARENT = 'CHILD_SHARE_FAILS_PARENT'
    CIRCULAR_DEPENDENCY = 'CIRCULAR_DEPENDENCY'
    CLEAN_SERVICE_ERROR = 'CLEAN_SERVICE_ERROR'
    CLONE_FIELD_INTEGRITY_EXCEPTION = 'CLONE_FIELD_INTEGRITY_EXCEPTION'
    CLONE_NOT_SUPPORTED = 'CLONE_NOT_SUPPORTED'
    CMS_FOLDER_ITEM_MOVE_FAILED = 'CMS_FOLDER_ITEM_MOVE_FAILED'
    COLLISION_DETECTED = 'COLLISION_DETECTED'
    COMMERCE_SEARCH_INDEXING_SYSTEM_ERROR = 'COMMERCE_SEARCH_INDEXING_SYSTEM_ERROR'
    COMMERCE_SEARCH_MQ_ERROR = 'COMMERCE_SEARCH_MQ_ERROR'
    COMMERCE_SEARCH_PROVIDER_LIMIT_EXCEEDED = 'COMMERCE_SEARCH_PROVIDER_LIMIT_EXCEEDED'
    COMMERCE_SEARCH_RESOURCE_NOT_FOUND = 'COMMERCE_SEARCH_RESOURCE_NOT_FOUND'
    COMMERCIAL_CONTROL_ERROR = 'COMMERCIAL_CONTROL_ERROR'
    COMMUNITY_NOT_ACCESSIBLE = 'COMMUNITY_NOT_ACCESSIBLE'
    CONFLICT = 'CONFLICT'
    CONFLICTING_ENVIRONMENT_HUB_MEMBER = 'CONFLICTING_ENVIRONMENT_HUB_MEMBER'
    CONFLICTING_SSO_USER_MAPPING = 'CONFLICTING_SSO_USER_MAPPING'
    CONTENT_NOT_FOUND = 'CONTENT_NOT_FOUND'
    CONTENT_SEARCH_NOT_ENABLED = 'CONTENT_SEARCH_NOT_ENABLED'
    CONTENT_TYPE_NOT_FOUND = 'CONTENT_TYPE_NOT_FOUND'
    CUSTOM_APEX_ERROR = 'CUSTOM_APEX_ERROR'
    CUSTOM_CLOB_FIELD_LIMIT_EXCEEDED = 'CUSTOM_CLOB_FIELD_LIMIT_EXCEEDED'
    CUSTOM_ENTITY_OR_FIELD_LIMIT = 'CUSTOM_ENTITY_OR_FIELD_LIMIT'
    CUSTOM_FIELD_INDEX_LIMIT_EXCEEDED = 'CUSTOM_FIELD_INDEX_LIMIT_EXCEEDED'
    CUSTOM_INDEX_EXISTS = 'CUSTOM_INDEX_EXISTS'
    CUSTOM_LINK_LIMIT_EXCEEDED = 'CUSTOM_LINK_LIMIT_EXCEEDED'
    CUSTOM_METADATA_LIMIT_EXCEEDED = 'CUSTOM_METADATA_LIMIT_EXCEEDED'
    CUSTOM_METADATA_REL_FIELD_MANAGEABILITY = 'CUSTOM_METADATA_REL_FIELD_MANAGEABILITY'
    CUSTOM_SETTINGS_LIMIT_EXCEEDED = 'CUSTOM_SETTINGS_LIMIT_EXCEEDED'
    CUSTOM_TAB_LIMIT_EXCEEDED = 'CUSTOM_TAB_LIMIT_EXCEEDED'
    DATAASSESSMENT_CONFIG_ASSESSMENT_IN_PROGRESS_ERROR = 'DATAASSESSMENT_CONFIG_ASSESSMENT_IN_PROGRESS_ERROR'
    DATAASSESSMENT_CONFIG_SERVICE_ERROR = 'DATAASSESSMENT_CONFIG_SERVICE_ERROR'
    DATACLOUDADDRESS_NO_RECORDS_FOUND = 'DATACLOUDADDRESS_NO_RECORDS_FOUND'
    DATACLOUDADDRESS_PROCESSING_ERROR = 'DATACLOUDADDRESS_PROCESSING_ERROR'
    DATACLOUDADDRESS_SERVER_ERROR = 'DATACLOUDADDRESS_SERVER_ERROR'
    DATA_MAPPING_NOT_FOUND = 'DATA_MAPPING_NOT_FOUND'
    DATA_MAPPING_SCHEMA_NOT_FOUND = 'DATA_MAPPING_SCHEMA_NOT_FOUND'
    DATA_TRANSFER_RECORD_LIMIT_EXCEEDED = 'DATA_TRANSFER_RECORD_LIMIT_EXCEEDED'
    DATA_TYPE_NOT_SUPPORTED = 'DATA_TYPE_NOT_SUPPORTED'
    DATE_OUT_OF_RANGE = 'DATE_OUT_OF_RANGE'
    DELETE_FAILED = 'DELETE_FAILED'
    DELETE_NOT_ALLOWED = 'DELETE_NOT_ALLOWED'
    DELETE_OPERATION_TOO_LARGE = 'DELETE_OPERATION_TOO_LARGE'
    DELETE_REQUIRED_ON_CASCADE = 'DELETE_REQUIRED_ON_CASCADE'
    DEPENDENCY_EXISTS = 'DEPENDENCY_EXISTS'
    DUPLICATES_DETECTED = 'DUPLICATES_DETECTED'
    DUPLICATE_CASE_SOLUTION = 'DUPLICATE_CASE_SOLUTION'
    DUPLICATE_COMM_NICKNAME = 'DUPLICATE_COMM_NICKNAME'
    DUPLICATE_CUSTOM_ENTITY_DEFINITION = 'DUPLICATE_CUSTOM_ENTITY_DEFINITION'
    DUPLICATE_CUSTOM_TAB_MOTIF = 'DUPLICATE_CUSTOM_TAB_MOTIF'
    DUPLICATE_DEVELOPER_NAME = 'DUPLICATE_DEVELOPER_NAME'
    DUPLICATE_EXTERNAL_ID = 'DUPLICATE_EXTERNAL_ID'
    DUPLICATE_MASTER_LABEL = 'DUPLICATE_MASTER_LABEL'
    DUPLICATE_SENDER_DISPLAY_NAME = 'DUPLICATE_SENDER_DISPLAY_NAME'
    DUPLICATE_USERNAME = 'DUPLICATE_USERNAME'
    DUPLICATE_VALUE = 'DUPLICATE_VALUE'
    EMAIL_ADDRESS_BOUNCED = 'EMAIL_ADDRESS_BOUNCED'
    EMAIL_EXTERNAL_TRANSPORT_CONNECTION_ERROR = 'EMAIL_EXTERNAL_TRANSPORT_CONNECTION_ERROR'
    EMAIL_EXTERNAL_TRANSPORT_PERMISSION_ERROR = 'EMAIL_EXTERNAL_TRANSPORT_PERMISSION_ERROR'
    EMAIL_EXTERNAL_TRANSPORT_TOKEN_ERROR = 'EMAIL_EXTERNAL_TRANSPORT_TOKEN_ERROR'
    EMAIL_EXTERNAL_TRANSPORT_TOO_LARGE_ERROR = 'EMAIL_EXTERNAL_TRANSPORT_TOO_LARGE_ERROR'
    EMAIL_EXTERNAL_TRANSPORT_TOO_MANY_REQUESTS_ERROR = 'EMAIL_EXTERNAL_TRANSPORT_TOO_MANY_REQUESTS_ERROR'
    EMAIL_EXTERNAL_TRANSPORT_UNKNOWN_ERROR = 'EMAIL_EXTERNAL_TRANSPORT_UNKNOWN_ERROR'
    EMAIL_NOT_PROCESSED_DUE_TO_PRIOR_ERROR = 'EMAIL_NOT_PROCESSED_DUE_TO_PRIOR_ERROR'
    EMAIL_OPTED_OUT = 'EMAIL_OPTED_OUT'
    EMAIL_TEMPLATE_FORMULA_ERROR = 'EMAIL_TEMPLATE_FORMULA_ERROR'
    EMAIL_TEMPLATE_MERGEFIELD_ACCESS_ERROR = 'EMAIL_TEMPLATE_MERGEFIELD_ACCESS_ERROR'
    EMAIL_TEMPLATE_MERGEFIELD_ERROR = 'EMAIL_TEMPLATE_MERGEFIELD_ERROR'
    EMAIL_TEMPLATE_MERGEFIELD_VALUE_ERROR = 'EMAIL_TEMPLATE_MERGEFIELD_VALUE_ERROR'
    EMAIL_TEMPLATE_PROCESSING_ERROR = 'EMAIL_TEMPLATE_PROCESSING_ERROR'
    EMPTY_INGESTION_JOB = 'EMPTY_INGESTION_JOB'
    EMPTY_SCONTROL_FILE_NAME = 'EMPTY_SCONTROL_FILE_NAME'
    ENHANCED_EMAIL_TEMPLATE_COMPILATION_ERROR = 'ENHANCED_EMAIL_TEMPLATE_COMPILATION_ERROR'
    ENTITY_FAILED_IFLASTMODIFIED_ON_UPDATE = 'ENTITY_FAILED_IFLASTMODIFIED_ON_UPDATE'
    ENTITY_IS_ARCHIVED = 'ENTITY_IS_ARCHIVED'
    ENTITY_IS_DELETED = 'ENTITY_IS_DELETED'
    ENTITY_IS_LOCKED = 'ENTITY_IS_LOCKED'
    ENTITY_SAVE_ERROR = 'ENTITY_SAVE_ERROR'
    ENTITY_SAVE_VALIDATION_ERROR = 'ENTITY_SAVE_VALIDATION_ERROR'
    ENVIRONMENT_HUB_MEMBERSHIP_CONFLICT = 'ENVIRONMENT_HUB_MEMBERSHIP_CONFLICT'
    ENVIRONMENT_HUB_MEMBERSHIP_ERROR_JOINING_HUB = 'ENVIRONMENT_HUB_MEMBERSHIP_ERROR_JOINING_HUB'
    ENVIRONMENT_HUB_MEMBERSHIP_USER_ALREADY_IN_HUB = 'ENVIRONMENT_HUB_MEMBERSHIP_USER_ALREADY_IN_HUB'
    ENVIRONMENT_HUB_MEMBERSHIP_USER_NOT_ORG_ADMIN = 'ENVIRONMENT_HUB_MEMBERSHIP_USER_NOT_ORG_ADMIN'
    ERROR_CALCULATING_EXPIRY_DATE = 'ERROR_CALCULATING_EXPIRY_DATE'
    ERROR_IN_MAILER = 'ERROR_IN_MAILER'
    EXCEEDED_MAX_SEMIJOIN_SUBSELECTS_WRITE = 'EXCEEDED_MAX_SEMIJOIN_SUBSELECTS_WRITE'
    EXCHANGE_WEB_SERVICES_URL_INVALID = 'EXCHANGE_WEB_SERVICES_URL_INVALID'
    EXTERNAL_RESOURCE_FORBIDDEN = 'EXTERNAL_RESOURCE_FORBIDDEN'
    FAILED_ACTIVATION = 'FAILED_ACTIVATION'
    FAILED_DUE_TO_OTHER_INPUTS = 'FAILED_DUE_TO_OTHER_INPUTS'
    FAILED_TO_RESOLVE_MAPPING = 'FAILED_TO_RESOLVE_MAPPING'
    FAILED_TO_RESOLVE_SCHEMA_INFORMATION = 'FAILED_TO_RESOLVE_SCHEMA_INFORMATION'
    FIELD_CUSTOM_VALIDATION_EXCEPTION = 'FIELD_CUSTOM_VALIDATION_EXCEPTION'
    FIELD_FILTER_VALIDATION_EXCEPTION = 'FIELD_FILTER_VALIDATION_EXCEPTION'
    FIELD_INTEGRITY_EXCEPTION = 'FIELD_INTEGRITY_EXCEPTION'
    FIELD_KEYWORD_LIST_MATCH_LIMIT = 'FIELD_KEYWORD_LIST_MATCH_LIMIT'
    FIELD_MAPPING_ERROR = 'FIELD_MAPPING_ERROR'
    FIELD_MODERATION_RULE_BLOCK = 'FIELD_MODERATION_RULE_BLOCK'
    FIELD_NOT_UPDATABLE = 'FIELD_NOT_UPDATABLE'
    FILE_EXTENSION_NOT_ALLOWED = 'FILE_EXTENSION_NOT_ALLOWED'
    FILE_SIZE_LIMIT_EXCEEDED = 'FILE_SIZE_LIMIT_EXCEEDED'
    FILTERED_LOOKUP_LIMIT_EXCEEDED = 'FILTERED_LOOKUP_LIMIT_EXCEEDED'
    FIND_DUPLICATES_ERROR = 'FIND_DUPLICATES_ERROR'
    FLOW_EXCEPTION = 'FLOW_EXCEPTION'
    FUNCTIONALITY_NOT_ENABLED = 'FUNCTIONALITY_NOT_ENABLED'
    GET_EINSTEIN_TENANT_ERROR = 'GET_EINSTEIN_TENANT_ERROR'
    HAS_PUBLIC_REFERENCES = 'HAS_PUBLIC_REFERENCES'
    HTML_FILE_UPLOAD_NOT_ALLOWED = 'HTML_FILE_UPLOAD_NOT_ALLOWED'
    IAS_AM_AUTH_BAD_REQUEST = 'IAS_AM_AUTH_BAD_REQUEST'
    IAS_AM_AUTH_UNAUTHORIZED = 'IAS_AM_AUTH_UNAUTHORIZED'
    IAS_INVALID_AUTH = 'IAS_INVALID_AUTH'
    IAS_INVALID_REQUEST_PARAMETER = 'IAS_INVALID_REQUEST_PARAMETER'
    IAS_RECORD_DOES_NOT_EXIST = 'IAS_RECORD_DOES_NOT_EXIST'
    IAS_TENANT_NOT_PROVISIONED = 'IAS_TENANT_NOT_PROVISIONED'
    IAS_UNCOMMITTED_WORK = 'IAS_UNCOMMITTED_WORK'
    IMAGE_TOO_LARGE = 'IMAGE_TOO_LARGE'
    INACTIVE_OWNER_OR_USER = 'INACTIVE_OWNER_OR_USER'
    INACTIVE_RULE_ERROR = 'INACTIVE_RULE_ERROR'
    INDEX_ITEM_LIMIT_EXCEEDED = 'INDEX_ITEM_LIMIT_EXCEEDED'
    INDEX_PAYLOAD_NOT_FOUND = 'INDEX_PAYLOAD_NOT_FOUND'
    INGESTION_JOB_RECORDS_LIMIT_EXCEEDED = 'INGESTION_JOB_RECORDS_LIMIT_EXCEEDED'
    INGESTION_TOTAL_FILE_SIZE_LIMIT_EXCEEDED = 'INGESTION_TOTAL_FILE_SIZE_LIMIT_EXCEEDED'
    INPUTPARAM_INCOMPATIBLE_DATATYPE = 'INPUTPARAM_INCOMPATIBLE_DATATYPE'
    INSERT_UPDATE_DELETE_NOT_ALLOWED_DURING_MAINTENANCE = 'INSERT_UPDATE_DELETE_NOT_ALLOWED_DURING_MAINTENANCE'
    INSUFFICIENT_ACCESS = 'INSUFFICIENT_ACCESS'
    INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY = 'INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY'
    INSUFFICIENT_ACCESS_OR_READONLY = 'INSUFFICIENT_ACCESS_OR_READONLY'
    INSUFFICIENT_ACCESS_TO_INSIGHTSEXTERNALDATA = 'INSUFFICIENT_ACCESS_TO_INSIGHTSEXTERNALDATA'
    INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE'
    INSUFFICIENT_CREDITS = 'INSUFFICIENT_CREDITS'
    INTEGRATION_CANCELLED = 'INTEGRATION_CANCELLED'
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    INVALID_ACCESS_LEVEL = 'INVALID_ACCESS_LEVEL'
    INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN'
    INVALID_ACCOUNT = 'INVALID_ACCOUNT'
    INVALID_API_INPUT = 'INVALID_API_INPUT'
    INVALID_ARGUMENT_TYPE = 'INVALID_ARGUMENT_TYPE'
    INVALID_ASSIGNEE_TYPE = 'INVALID_ASSIGNEE_TYPE'
    INVALID_ASSIGNMENT_RULE = 'INVALID_ASSIGNMENT_RULE'
    INVALID_AUTH_HEADER = 'INVALID_AUTH_HEADER'
    INVALID_BATCH_OPERATION = 'INVALID_BATCH_OPERATION'
    INVALID_CHECKOUT_INPUT = 'INVALID_CHECKOUT_INPUT'
    INVALID_CONTACT = 'INVALID_CONTACT'
    INVALID_CONTENT_TYPE = 'INVALID_CONTENT_TYPE'
    INVALID_CREDIT_CARD_INFO = 'INVALID_CREDIT_CARD_INFO'
    INVALID_CROSS_REFERENCE_KEY = 'INVALID_CROSS_REFERENCE_KEY'
    INVALID_CROSS_REFERENCE_TYPE_FOR_FIELD = 'INVALID_CROSS_REFERENCE_TYPE_FOR_FIELD'
    INVALID_CURRENCY_CONV_RATE = 'INVALID_CURRENCY_CONV_RATE'
    INVALID_CURRENCY_CORP_RATE = 'INVALID_CURRENCY_CORP_RATE'
    INVALID_CURRENCY_ISO = 'INVALID_CURRENCY_ISO'
    INVALID_DATASET_REFERENCE_INPUT = 'INVALID_DATASET_REFERENCE_INPUT'
    INVALID_DATA_CATEGORY_GROUP_REFERENCE = 'INVALID_DATA_CATEGORY_GROUP_REFERENCE'
    INVALID_DATA_URI = 'INVALID_DATA_URI'
    INVALID_EMAIL_ADDRESS = 'INVALID_EMAIL_ADDRESS'
    INVALID_EMPTY_KEY_OWNER = 'INVALID_EMPTY_KEY_OWNER'
    INVALID_ENTITY_FOR_MATCH_ENGINE_ERROR = 'INVALID_ENTITY_FOR_MATCH_ENGINE_ERROR'
    INVALID_ENTITY_FOR_MATCH_OPERATION_ERROR = 'INVALID_ENTITY_FOR_MATCH_OPERATION_ERROR'
    INVALID_ENTITY_FOR_UPSERT = 'INVALID_ENTITY_FOR_UPSERT'
    INVALID_ENVIRONMENT_HUB_MEMBER = 'INVALID_ENVIRONMENT_HUB_MEMBER'
    INVALID_EVENT_DELIVERY = 'INVALID_EVENT_DELIVERY'
    INVALID_EVENT_INPUT = 'INVALID_EVENT_INPUT'
    INVALID_EVENT_SUBSCRIPTION = 'INVALID_EVENT_SUBSCRIPTION'
    INVALID_EXTENSION_ID = 'INVALID_EXTENSION_ID'
    INVALID_EXTERNAL_ID_FIELD_NAME = 'INVALID_EXTERNAL_ID_FIELD_NAME'
    INVALID_FIELD = 'INVALID_FIELD'
    INVALID_FIELD_FOR_INSERT_UPDATE = 'INVALID_FIELD_FOR_INSERT_UPDATE'
    INVALID_FIELD_WHEN_USING_TEMPLATE = 'INVALID_FIELD_WHEN_USING_TEMPLATE'
    INVALID_FILTER_ACTION = 'INVALID_FILTER_ACTION'
    INVALID_GOOGLE_DOCS_URL = 'INVALID_GOOGLE_DOCS_URL'
    INVALID_ID_FIELD = 'INVALID_ID_FIELD'
    INVALID_INET_ADDRESS = 'INVALID_INET_ADDRESS'
    INVALID_INPUT = 'INVALID_INPUT'
    INVALID_INPUT_FORMAT = 'INVALID_INPUT_FORMAT'
    INVALID_KEY_FIELD_INPUT = 'INVALID_KEY_FIELD_INPUT'
    INVALID_LINEITEM_CLONE_STATE = 'INVALID_LINEITEM_CLONE_STATE'
    INVALID_MARKUP = 'INVALID_MARKUP'
    INVALID_MASTER_OR_TRANSLATED_SOLUTION = 'INVALID_MASTER_OR_TRANSLATED_SOLUTION'
    INVALID_MERGE_RECORD = 'INVALID_MERGE_RECORD'
    INVALID_MESSAGE_ID_REFERENCE = 'INVALID_MESSAGE_ID_REFERENCE'
    INVALID_NAMESPACE_PREFIX = 'INVALID_NAMESPACE_PREFIX'
    INVALID_OAUTH_URL = 'INVALID_OAUTH_URL'
    INVALID_OPERATION = 'INVALID_OPERATION'
    INVALID_OPERATOR = 'INVALID_OPERATOR'
    INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST = 'INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST'
    INVALID_OWNER = 'INVALID_OWNER'
    INVALID_PACKAGE_LICENSE = 'INVALID_PACKAGE_LICENSE'
    INVALID_PACKAGE_VERSION = 'INVALID_PACKAGE_VERSION'
    INVALID_PARTNER_NETWORK_STATUS = 'INVALID_PARTNER_NETWORK_STATUS'
    INVALID_PAYLOAD_VERSION = 'INVALID_PAYLOAD_VERSION'
    INVALID_PERSON_ACCOUNT_OPERATION = 'INVALID_PERSON_ACCOUNT_OPERATION'
    INVALID_PROFILE = 'INVALID_PROFILE'
    INVALID_PROMOTION = 'INVALID_PROMOTION'
    INVALID_PROVIDER_TYPE = 'INVALID_PROVIDER_TYPE'
    INVALID_QUERY_KEY = 'INVALID_QUERY_KEY'
    INVALID_QUERY_LOCATOR = 'INVALID_QUERY_LOCATOR'
    INVALID_QUERY_VALUE = 'INVALID_QUERY_VALUE'
    INVALID_READ_ONLY_USER_DML = 'INVALID_READ_ONLY_USER_DML'
    INVALID_RECEIVEDDOCUMENTID_ATTACHMENT = 'INVALID_RECEIVEDDOCUMENTID_ATTACHMENT'
    INVALID_RECORD_TYPE = 'INVALID_RECORD_TYPE'
    INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN'
    INVALID_REQUEST_STATE = 'INVALID_REQUEST_STATE'
    INVALID_RUNTIME_VALUE = 'INVALID_RUNTIME_VALUE'
    INVALID_SAVE_AS_ACTIVITY_FLAG = 'INVALID_SAVE_AS_ACTIVITY_FLAG'
    INVALID_SCS_INBOUND_USER = 'INVALID_SCS_INBOUND_USER'
    INVALID_SEARCH_PROVIDER_REQUEST = 'INVALID_SEARCH_PROVIDER_REQUEST'
    INVALID_SESSION_ID = 'INVALID_SESSION_ID'
    INVALID_SETUP_OWNER = 'INVALID_SETUP_OWNER'
    INVALID_SIGNUP_COUNTRY = 'INVALID_SIGNUP_COUNTRY'
    INVALID_SIGNUP_OPTION = 'INVALID_SIGNUP_OPTION'
    INVALID_SITE_DELETE_EXCEPTION = 'INVALID_SITE_DELETE_EXCEPTION'
    INVALID_SITE_FILE_IMPORTED_EXCEPTION = 'INVALID_SITE_FILE_IMPORTED_EXCEPTION'
    INVALID_SITE_FILE_TYPE_EXCEPTION = 'INVALID_SITE_FILE_TYPE_EXCEPTION'
    INVALID_SOURCE_OBJECT_ID = 'INVALID_SOURCE_OBJECT_ID'
    INVALID_STATUS = 'INVALID_STATUS'
    INVALID_SUBDOMAIN = 'INVALID_SUBDOMAIN'
    INVALID_TARGET_OBJECT_NAME = 'INVALID_TARGET_OBJECT_NAME'
    INVALID_TEXT_REPRESENTATION = 'INVALID_TEXT_REPRESENTATION'
    INVALID_TYPE = 'INVALID_TYPE'
    INVALID_TYPE_FOR_OPERATION = 'INVALID_TYPE_FOR_OPERATION'
    INVALID_TYPE_ON_FIELD_IN_RECORD = 'INVALID_TYPE_ON_FIELD_IN_RECORD'
    INVALID_UNMERGE_RECORD = 'INVALID_UNMERGE_RECORD'
    INVALID_USERID = 'INVALID_USERID'
    INVALID_USER_OBJECT = 'INVALID_USER_OBJECT'
    IP_RANGE_LIMIT_EXCEEDED = 'IP_RANGE_LIMIT_EXCEEDED'
    ITEM_NOT_FOUND = 'ITEM_NOT_FOUND'
    JIGSAW_IMPORT_LIMIT_EXCEEDED = 'JIGSAW_IMPORT_LIMIT_EXCEEDED'
    LICENSE_LIMIT_EXCEEDED = 'LICENSE_LIMIT_EXCEEDED'
    LIGHT_PORTAL_USER_EXCEPTION = 'LIGHT_PORTAL_USER_EXCEPTION'
    LIMIT_EXCEEDED = 'LIMIT_EXCEEDED'
    LIST_PRICE_NOT_FOUND = 'LIST_PRICE_NOT_FOUND'
    MALFORMED_ID = 'MALFORMED_ID'
    MANAGER_NOT_DEFINED = 'MANAGER_NOT_DEFINED'
    MASSMAIL_RETRY_LIMIT_EXCEEDED = 'MASSMAIL_RETRY_LIMIT_EXCEEDED'
    MASS_MAIL_LIMIT_EXCEEDED = 'MASS_MAIL_LIMIT_EXCEEDED'
    MATCH_DEFINITION_ERROR = 'MATCH_DEFINITION_ERROR'
    MATCH_OPERATION_ERROR = 'MATCH_OPERATION_ERROR'
    MATCH_OPERATION_INVALID_ENGINE_ERROR = 'MATCH_OPERATION_INVALID_ENGINE_ERROR'
    MATCH_OPERATION_INVALID_RULE_ERROR = 'MATCH_OPERATION_INVALID_RULE_ERROR'
    MATCH_OPERATION_MISSING_ENGINE_ERROR = 'MATCH_OPERATION_MISSING_ENGINE_ERROR'
    MATCH_OPERATION_MISSING_OBJECT_TYPE_ERROR = 'MATCH_OPERATION_MISSING_OBJECT_TYPE_ERROR'
    MATCH_OPERATION_MISSING_OPTIONS_ERROR = 'MATCH_OPERATION_MISSING_OPTIONS_ERROR'
    MATCH_OPERATION_MISSING_RULE_ERROR = 'MATCH_OPERATION_MISSING_RULE_ERROR'
    MATCH_OPERATION_UNKNOWN_RULE_ERROR = 'MATCH_OPERATION_UNKNOWN_RULE_ERROR'
    MATCH_OPERATION_UNSUPPORTED_VERSION_ERROR = 'MATCH_OPERATION_UNSUPPORTED_VERSION_ERROR'
    MATCH_PRECONDITION_FAILED = 'MATCH_PRECONDITION_FAILED'
    MATCH_PRECONDITION_REQUIRED = 'MATCH_PRECONDITION_REQUIRED'
    MATCH_RUNTIME_ERROR = 'MATCH_RUNTIME_ERROR'
    MATCH_SERVICE_ERROR = 'MATCH_SERVICE_ERROR'
    MATCH_SERVICE_TIMED_OUT = 'MATCH_SERVICE_TIMED_OUT'
    MATCH_SERVICE_UNAVAILABLE_ERROR = 'MATCH_SERVICE_UNAVAILABLE_ERROR'
    MAXIMUM_CCEMAILS_EXCEEDED = 'MAXIMUM_CCEMAILS_EXCEEDED'
    MAXIMUM_DASHBOARD_COMPONENTS_EXCEEDED = 'MAXIMUM_DASHBOARD_COMPONENTS_EXCEEDED'
    MAXIMUM_HIERARCHY_CHILDREN_REACHED = 'MAXIMUM_HIERARCHY_CHILDREN_REACHED'
    MAXIMUM_HIERARCHY_LEVELS_REACHED = 'MAXIMUM_HIERARCHY_LEVELS_REACHED'
    MAXIMUM_HIERARCHY_TREE_SIZE_REACHED = 'MAXIMUM_HIERARCHY_TREE_SIZE_REACHED'
    MAXIMUM_SIZE_OF_ATTACHMENT = 'MAXIMUM_SIZE_OF_ATTACHMENT'
    MAXIMUM_SIZE_OF_DOCUMENT = 'MAXIMUM_SIZE_OF_DOCUMENT'
    MAX_ACTIONS_PER_RULE_EXCEEDED = 'MAX_ACTIONS_PER_RULE_EXCEEDED'
    MAX_ACTIVE_RULES_EXCEEDED = 'MAX_ACTIVE_RULES_EXCEEDED'
    MAX_APPROVAL_STEPS_EXCEEDED = 'MAX_APPROVAL_STEPS_EXCEEDED'
    MAX_DEPTH_IN_FLOW_EXECUTION = 'MAX_DEPTH_IN_FLOW_EXECUTION'
    MAX_FORMULAS_PER_RULE_EXCEEDED = 'MAX_FORMULAS_PER_RULE_EXCEEDED'
    MAX_LIMIT_EXCEEDED = 'MAX_LIMIT_EXCEEDED'
    MAX_RULES_EXCEEDED = 'MAX_RULES_EXCEEDED'
    MAX_RULE_ENTRIES_EXCEEDED = 'MAX_RULE_ENTRIES_EXCEEDED'
    MAX_TASK_DESCRIPTION_EXCEEEDED = 'MAX_TASK_DESCRIPTION_EXCEEEDED'
    MAX_TM_RULES_EXCEEDED = 'MAX_TM_RULES_EXCEEDED'
    MAX_TM_RULE_ITEMS_EXCEEDED = 'MAX_TM_RULE_ITEMS_EXCEEDED'
    MAX_TRIGGERS_EXCEEDED = 'MAX_TRIGGERS_EXCEEDED'
    MERGE_FAILED = 'MERGE_FAILED'
    METADATA_FIELD_UPDATE_ERROR = 'METADATA_FIELD_UPDATE_ERROR'
    METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED'
    MISMATCHING_TYPES = 'MISMATCHING_TYPES'
    MISSING_ARGUMENT = 'MISSING_ARGUMENT'
    MISSING_OMNI_PROCESS_ID = 'MISSING_OMNI_PROCESS_ID'
    MISSING_RECEIVEDDOCUMENTID_ATTACHMENT = 'MISSING_RECEIVEDDOCUMENTID_ATTACHMENT'
    MISSING_RECORD = 'MISSING_RECORD'
    MIXED_DML_OPERATION = 'MIXED_DML_OPERATION'
    MULTIPLE_CONTENT_FOUND = 'MULTIPLE_CONTENT_FOUND'
    MULTIPLE_VOUCHERS = 'MULTIPLE_VOUCHERS'
    NONUNIQUE_SHIPPING_ADDRESS = 'NONUNIQUE_SHIPPING_ADDRESS'
    NOT_FOUND = 'NOT_FOUND'
    NOT_RECOVERABLE_SEARCH_PROVIDER_ERROR = 'NOT_RECOVERABLE_SEARCH_PROVIDER_ERROR'
    NO_ACCESS_TOKEN = 'NO_ACCESS_TOKEN'
    NO_ACCESS_TOKEN_FROM_REFRESH = 'NO_ACCESS_TOKEN_FROM_REFRESH'
    NO_APPLICABLE_PROCESS = 'NO_APPLICABLE_PROCESS'
    NO_ATTACHMENT_PERMISSION = 'NO_ATTACHMENT_PERMISSION'
    NO_AUTH_PROVIDER = 'NO_AUTH_PROVIDER'
    NO_INACTIVE_DIVISION_MEMBERS = 'NO_INACTIVE_DIVISION_MEMBERS'
    NO_MASS_MAIL_PERMISSION = 'NO_MASS_MAIL_PERMISSION'
    NO_PARTNER_PERMISSION = 'NO_PARTNER_PERMISSION'
    NO_REFRESH_TOKEN = 'NO_REFRESH_TOKEN'
    NO_SEARCH_ATTRIBUTES = 'NO_SEARCH_ATTRIBUTES'
    NO_SINGLE_MAIL_PERMISSION = 'NO_SINGLE_MAIL_PERMISSION'
    NO_SORT_PRICEBOOK_ASSOCIATED_ERROR = 'NO_SORT_PRICEBOOK_ASSOCIATED_ERROR'
    NO_SUCH_USER_EXISTS = 'NO_SUCH_USER_EXISTS'
    NO_TOKEN_ENDPOINT = 'NO_TOKEN_ENDPOINT'
    NUMBER_OUTSIDE_VALID_RANGE = 'NUMBER_OUTSIDE_VALID_RANGE'
    NUM_HISTORY_FIELDS_BY_SOBJECT_EXCEEDED = 'NUM_HISTORY_FIELDS_BY_SOBJECT_EXCEEDED'
    OCR_INVALID_REQUEST = 'OCR_INVALID_REQUEST'
    OPERATION_ENQUEUED = 'OPERATION_ENQUEUED'
    OPTED_OUT_OF_MASS_MAIL = 'OPTED_OUT_OF_MASS_MAIL'
    OP_WITH_INVALID_USER_TYPE_EXCEPTION = 'OP_WITH_INVALID_USER_TYPE_EXCEPTION'
    ORCHESTRATION_INVALID = 'ORCHESTRATION_INVALID'
    ORDER_MANAGEMENT_ACTION_NOT_ALLOWED = 'ORDER_MANAGEMENT_ACTION_NOT_ALLOWED'
    ORDER_MANAGEMENT_INVALID_RECORD = 'ORDER_MANAGEMENT_INVALID_RECORD'
    ORDER_MANAGEMENT_RECORD_EXISTS = 'ORDER_MANAGEMENT_RECORD_EXISTS'
    ORDER_MANAGEMENT_RECORD_NOT_FOUND = 'ORDER_MANAGEMENT_RECORD_NOT_FOUND'
    PACKAGE_DISABLED = 'PACKAGE_DISABLED'
    PACKAGE_LICENSE_REQUIRED = 'PACKAGE_LICENSE_REQUIRED'
    PACKAGING_API_INSTALL_FAILED = 'PACKAGING_API_INSTALL_FAILED'
    PACKAGING_API_UNINSTALL_FAILED = 'PACKAGING_API_UNINSTALL_FAILED'
    PALI_INVALID_ACTION_ID = 'PALI_INVALID_ACTION_ID'
    PALI_INVALID_ACTION_NAME = 'PALI_INVALID_ACTION_NAME'
    PALI_INVALID_ACTION_TYPE = 'PALI_INVALID_ACTION_TYPE'
    PAL_INVALID_ASSISTANT_RECOMMENDATION_TYPE_ID = 'PAL_INVALID_ASSISTANT_RECOMMENDATION_TYPE_ID'
    PAL_INVALID_ENTITY_ID = 'PAL_INVALID_ENTITY_ID'
    PAL_INVALID_FLEXIPAGE_ID = 'PAL_INVALID_FLEXIPAGE_ID'
    PAL_INVALID_LAYOUT_ID = 'PAL_INVALID_LAYOUT_ID'
    PAL_INVALID_PARAMETERS = 'PAL_INVALID_PARAMETERS'
    PARAMETER_TOO_LARGE = 'PARAMETER_TOO_LARGE'
    PARTICIPANT_RELATIONSHIP_EXISTS = 'PARTICIPANT_RELATIONSHIP_EXISTS'
    PAYLOAD_SIZE_EXCEEDED = 'PAYLOAD_SIZE_EXCEEDED'
    PA_API_EXCEPTION = 'PA_API_EXCEPTION'
    PA_AXIS_FAULT = 'PA_AXIS_FAULT'
    PA_INVALID_ID_EXCEPTION = 'PA_INVALID_ID_EXCEPTION'
    PA_NO_ACCESS_EXCEPTION = 'PA_NO_ACCESS_EXCEPTION'
    PA_NO_DATA_FOUND_EXCEPTION = 'PA_NO_DATA_FOUND_EXCEPTION'
    PA_URI_SYNTAX_EXCEPTION = 'PA_URI_SYNTAX_EXCEPTION'
    PA_VISIBLE_ACTIONS_FILTER_ORDERING_EXCEPTION = 'PA_VISIBLE_ACTIONS_FILTER_ORDERING_EXCEPTION'
    PENDING_COMMIT = 'PENDING_COMMIT'
    PICKLIST_INACTIVE_VALUES_EXCEEDED = 'PICKLIST_INACTIVE_VALUES_EXCEEDED'
    PLATFORM_EVENT_ENCRYPTION_ERROR = 'PLATFORM_EVENT_ENCRYPTION_ERROR'
    PLATFORM_EVENT_PUBLISHING_UNAVAILABLE = 'PLATFORM_EVENT_PUBLISHING_UNAVAILABLE'
    PLATFORM_EVENT_PUBLISH_FAILED = 'PLATFORM_EVENT_PUBLISH_FAILED'
    PORTAL_NO_ACCESS = 'PORTAL_NO_ACCESS'
    PORTAL_USER_ALREADY_EXISTS_FOR_CONTACT = 'PORTAL_USER_ALREADY_EXISTS_FOR_CONTACT'
    PORTAL_USER_CREATION_RESTRICTED_WITH_ENCRYPTION = 'PORTAL_USER_CREATION_RESTRICTED_WITH_ENCRYPTION'
    PRICE_NOT_FOUND = 'PRICE_NOT_FOUND'
    PRIVATE_CONTACT_ON_ASSET = 'PRIVATE_CONTACT_ON_ASSET'
    PROCESSING_HALTED = 'PROCESSING_HALTED'
    PROGRAM_PROGRESS_NOT_ACTIVE = 'PROGRAM_PROGRESS_NOT_ACTIVE'
    QA_INVALID_CREATE_FEED_ITEM = 'QA_INVALID_CREATE_FEED_ITEM'
    QA_INVALID_SUCCESS_MESSAGE = 'QA_INVALID_SUCCESS_MESSAGE'
    QUERY_REFINEMENT_VALUE_LIMIT_EXCEEDED = 'QUERY_REFINEMENT_VALUE_LIMIT_EXCEEDED'
    QUERY_TIMEOUT = 'QUERY_TIMEOUT'
    QUICK_ACTION_LIST_ITEM_NOT_ALLOWED = 'QUICK_ACTION_LIST_ITEM_NOT_ALLOWED'
    QUICK_ACTION_LIST_NOT_ALLOWED = 'QUICK_ACTION_LIST_NOT_ALLOWED'
    RECORD_CREATION_FAILED = 'RECORD_CREATION_FAILED'
    RECORD_IN_USE_BY_WORKFLOW = 'RECORD_IN_USE_BY_WORKFLOW'
    RECORD_UPDATE_FAILED = 'RECORD_UPDATE_FAILED'
    RECOVERABLE_SEARCH_PROVIDER_ERROR = 'RECOVERABLE_SEARCH_PROVIDER_ERROR'
    RELATED_ENTITY_FILTER_VALIDATION_EXCEPTION = 'RELATED_ENTITY_FILTER_VALIDATION_EXCEPTION'
    REL_FIELD_BAD_ACCESSIBILITY = 'REL_FIELD_BAD_ACCESSIBILITY'
    REPUTATION_MINIMUM_NUMBER_NOT_REACHED = 'REPUTATION_MINIMUM_NUMBER_NOT_REACHED'
    REQUEST_RUNNING_TOO_LONG = 'REQUEST_RUNNING_TOO_LONG'
    REQUIRED_FEATURE_MISSING = 'REQUIRED_FEATURE_MISSING'
    REQUIRED_FIELD_MISSING = 'REQUIRED_FIELD_MISSING'
    REQUIRE_CONNECTED_APP_SCS = 'REQUIRE_CONNECTED_APP_SCS'
    REQUIRE_CONNECTED_APP_SESSION_SCS = 'REQUIRE_CONNECTED_APP_SESSION_SCS'
    REQUIRE_RUNAS_USER = 'REQUIRE_RUNAS_USER'
    RETRIEVE_EXCHANGE_ATTACHMENT_FAILED = 'RETRIEVE_EXCHANGE_ATTACHMENT_FAILED'
    RETRIEVE_EXCHANGE_EMAIL_FAILED = 'RETRIEVE_EXCHANGE_EMAIL_FAILED'
    RETRIEVE_EXCHANGE_EVENT_FAILED = 'RETRIEVE_EXCHANGE_EVENT_FAILED'
    RETRIEVE_GOOGLE_EMAIL_FAILED = 'RETRIEVE_GOOGLE_EMAIL_FAILED'
    RETRIEVE_GOOGLE_EVENT_FAILED = 'RETRIEVE_GOOGLE_EVENT_FAILED'
    RETRIEVE_USER_CONFIG_ERROR = 'RETRIEVE_USER_CONFIG_ERROR'
    ROUTES_EVALUATION_LIMIT_EXCEEDED = 'ROUTES_EVALUATION_LIMIT_EXCEEDED'
    SALESFORCE_INBOX_TRANSPORT_CONNECTION_ERROR = 'SALESFORCE_INBOX_TRANSPORT_CONNECTION_ERROR'
    SALESFORCE_INBOX_TRANSPORT_INVALID_INPUT_ERROR = 'SALESFORCE_INBOX_TRANSPORT_INVALID_INPUT_ERROR'
    SALESFORCE_INBOX_TRANSPORT_TOKEN_ERROR = 'SALESFORCE_INBOX_TRANSPORT_TOKEN_ERROR'
    SALESFORCE_INBOX_TRANSPORT_UNKNOWN_ERROR = 'SALESFORCE_INBOX_TRANSPORT_UNKNOWN_ERROR'
    SCHEMA_OBJECT_NOT_FOUND = 'SCHEMA_OBJECT_NOT_FOUND'
    SEARCH_PROVIDER_REQUEST_RATE_EXCEEDED = 'SEARCH_PROVIDER_REQUEST_RATE_EXCEEDED'
    SELF_REFERENCE_FROM_FLOW = 'SELF_REFERENCE_FROM_FLOW'
    SELF_REFERENCE_FROM_TRIGGER = 'SELF_REFERENCE_FROM_TRIGGER'
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
    SESSION_EXPIRED = 'SESSION_EXPIRED'
    SESSION_INVALIDATED = 'SESSION_INVALIDATED'
    SHARE_NEEDED_FOR_CHILD_OWNER = 'SHARE_NEEDED_FOR_CHILD_OWNER'
    SINGLE_EMAIL_LIMIT_EXCEEDED = 'SINGLE_EMAIL_LIMIT_EXCEEDED'
    SLACK_API_ERROR = 'SLACK_API_ERROR'
    SOCIAL_ACCOUNT_NOT_FOUND = 'SOCIAL_ACCOUNT_NOT_FOUND'
    SOCIAL_ACTION_INVALID = 'SOCIAL_ACTION_INVALID'
    SOCIAL_PERSONA_NOT_FOUND = 'SOCIAL_PERSONA_NOT_FOUND'
    SOCIAL_POST_INVALID = 'SOCIAL_POST_INVALID'
    SOCIAL_POST_NOT_FOUND = 'SOCIAL_POST_NOT_FOUND'
    SPECIFICATION_GENERATION_EXCEPTION = 'SPECIFICATION_GENERATION_EXCEPTION'
    STANDARD_PRICE_NOT_DEFINED = 'STANDARD_PRICE_NOT_DEFINED'
    STORAGE_LIMIT_EXCEEDED = 'STORAGE_LIMIT_EXCEEDED'
    STRING_TOO_LONG = 'STRING_TOO_LONG'
    SUBDOMAIN_IN_USE = 'SUBDOMAIN_IN_USE'
    TABSET_LIMIT_EXCEEDED = 'TABSET_LIMIT_EXCEEDED'
    TEMPLATE_NOT_ACTIVE = 'TEMPLATE_NOT_ACTIVE'
    TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND'
    TERMS_OF_SERVICE_UNREAD = 'TERMS_OF_SERVICE_UNREAD'
    TERRITORY_REALIGN_IN_PROGRESS = 'TERRITORY_REALIGN_IN_PROGRESS'
    TEXT_DATA_OUTSIDE_SUPPORTED_CHARSET = 'TEXT_DATA_OUTSIDE_SUPPORTED_CHARSET'
    TEXT_TO_PICKLIST_VALUES_EXCEEDED = 'TEXT_TO_PICKLIST_VALUES_EXCEEDED'
    TOO_MANY_APEX_REQUESTS = 'TOO_MANY_APEX_REQUESTS'
    TOO_MANY_ENUM_VALUE = 'TOO_MANY_ENUM_VALUE'
    TOO_MANY_JOBS = 'TOO_MANY_JOBS'
    TOO_MANY_POSSIBLE_USERS_EXIST = 'TOO_MANY_POSSIBLE_USERS_EXIST'
    TRANSFER_REQUIRES_READ = 'TRANSFER_REQUIRES_READ'
    UISF_ENTITY_QUERY_FAILED = 'UISF_ENTITY_QUERY_FAILED'
    UISF_NO_MAPPINGS_FOUND = 'UISF_NO_MAPPINGS_FOUND'
    UISF_TOKEN_NOT_FOUND = 'UISF_TOKEN_NOT_FOUND'
    UISF_UNKNOWN_EXCEPTION = 'UISF_UNKNOWN_EXCEPTION'
    UISF_USER_MAPPING_FAILED = 'UISF_USER_MAPPING_FAILED'
    UNABLE_TO_LOCK_ROW = 'UNABLE_TO_LOCK_ROW'
    UNAUTHORIZED_SEARCH_PROVIDER_REQUEST = 'UNAUTHORIZED_SEARCH_PROVIDER_REQUEST'
    UNAVAILABLE_RECORDTYPE_EXCEPTION = 'UNAVAILABLE_RECORDTYPE_EXCEPTION'
    UNAVAILABLE_REF = 'UNAVAILABLE_REF'
    UNDEFINED_MAPPING_DEFINITION = 'UNDEFINED_MAPPING_DEFINITION'
    UNDELETE_FAILED = 'UNDELETE_FAILED'
    UNKNOWN_EXCEPTION = 'UNKNOWN_EXCEPTION'
    UNKNOWN_TOKEN_ERROR = 'UNKNOWN_TOKEN_ERROR'
    UNQUALIFIED_CART = 'UNQUALIFIED_CART'
    UNSAFE_HTML_CONTENT = 'UNSAFE_HTML_CONTENT'
    UNSPECIFIED_EMAIL_ADDRESS = 'UNSPECIFIED_EMAIL_ADDRESS'
    UNSUPPORTED_APEX_TRIGGER_OPERATON = 'UNSUPPORTED_APEX_TRIGGER_OPERATON'
    UNSUPPORTED_MODE = 'UNSUPPORTED_MODE'
    UNSUPPORTED_PAYMENT_GATEWAY_TYPE = 'UNSUPPORTED_PAYMENT_GATEWAY_TYPE'
    UNSUPPORTED_PAYMENT_REQUEST_TYPE = 'UNSUPPORTED_PAYMENT_REQUEST_TYPE'
    UNSUPPORTED_SITE = 'UNSUPPORTED_SITE'
    UNSUPPORTED_SITE_FILE_IMPORTED_EXCEPTION = 'UNSUPPORTED_SITE_FILE_IMPORTED_EXCEPTION'
    UNSUPPORTED_SOCIAL_PROVIDER = 'UNSUPPORTED_SOCIAL_PROVIDER'
    UNVERIFIED_SENDER_ADDRESS = 'UNVERIFIED_SENDER_ADDRESS'
    UPDATE_GOOGLE_EMAIL_LABEL_FAILED = 'UPDATE_GOOGLE_EMAIL_LABEL_FAILED'
    USER_OWNS_PORTAL_ACCOUNT_EXCEPTION = 'USER_OWNS_PORTAL_ACCOUNT_EXCEPTION'
    USER_WITHOUT_WEM_PERMISSION = 'USER_WITHOUT_WEM_PERMISSION'
    USER_WITH_APEX_SHARES_EXCEPTION = 'USER_WITH_APEX_SHARES_EXCEPTION'
    VARIANT_NOT_FOUND = 'VARIANT_NOT_FOUND'
    VF_COMPILE_ERROR = 'VF_COMPILE_ERROR'
    WEBLINK_SIZE_LIMIT_EXCEEDED = 'WEBLINK_SIZE_LIMIT_EXCEEDED'
    WEBLINK_URL_INVALID = 'WEBLINK_URL_INVALID'
    WEM_SEGMENTS_CAN_NOT_HAVE_NON_ACTIVE_SEGMENT_TYPE = 'WEM_SEGMENTS_CAN_NOT_HAVE_NON_ACTIVE_SEGMENT_TYPE'
    WEM_SHIFT_SEGMENT_TIME_IS_OUTSIDE_OF_THE_SHIFT_DURATION = 'WEM_SHIFT_SEGMENT_TIME_IS_OUTSIDE_OF_THE_SHIFT_DURATION'
    WEM_USER_NOT_ORG_ADMIN = 'WEM_USER_NOT_ORG_ADMIN'
    WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND'
    WRONG_CONTROLLER_TYPE = 'WRONG_CONTROLLER_TYPE'
    XCLEAN_DJ_MATCH_IGNORABLE_ERROR = 'XCLEAN_DJ_MATCH_IGNORABLE_ERROR'
    XCLEAN_DJ_MATCH_INTERNAL_DJ_ERROR = 'XCLEAN_DJ_MATCH_INTERNAL_DJ_ERROR'
    XCLEAN_DJ_MATCH_NON_RETRIABLE_ERROR = 'XCLEAN_DJ_MATCH_NON_RETRIABLE_ERROR'
    XCLEAN_DJ_MATCH_RETRIABLE_ERROR = 'XCLEAN_DJ_MATCH_RETRIABLE_ERROR'
    XCLEAN_DJ_MATCH_UNKNOWN_ERROR = 'XCLEAN_DJ_MATCH_UNKNOWN_ERROR'
    XCLEAN_UNEXPECTED_ERROR = 'XCLEAN_UNEXPECTED_ERROR'


@salesforce_api_dataclass
class Error:
    exception_code: str = field(metadata={"alias": "exceptionCode"}, default=None)
    exception_message: str = field(metadata={"alias": "exceptionMessage"}, default=None)


@salesforce_api_dataclass
class JobInfo:
    id: str = field(metadata={"alias": "id"}, default=None)
    operation: OperationEnum = field(metadata={"alias": "operation"}, default=None)
    object: str = field(metadata={"alias": "object"}, default=None)
    created_by_id: str = field(metadata={"alias": "createdById"}, default=None)
    created_date: datetime = field(metadata={"alias": "createdDate"}, default=None)
    system_modstamp: datetime = field(metadata={"alias": "systemModstamp"}, default=None)
    state: JobStateEnum = field(metadata={"alias": "state"}, default=None)
    external_id_field_name: str = field(metadata={"alias": "externalIdFieldName"}, default=None)
    concurrency_mode: ConcurrencyModeEnum = field(metadata={"alias": "concurrencyMode"}, default=None)
    content_type: ContentType = field(metadata={"alias": "contentType"}, default=None)
    number_batches_queued: int = field(metadata={"alias": "numberBatchesQueued"}, default=None)
    number_batches_in_progress: int = field(metadata={"alias": "numberBatchesInProgress"}, default=None)
    number_batches_completed: int = field(metadata={"alias": "numberBatchesCompleted"}, default=None)
    number_batches_failed: int = field(metadata={"alias": "numberBatchesFailed"}, default=None)
    number_batches_total: int = field(metadata={"alias": "numberBatchesTotal"}, default=None)
    number_records_processed: int = field(metadata={"alias": "numberRecordsProcessed"}, default=None)
    number_retries: int = field(metadata={"alias": "numberRetries"}, default=None)
    api_version: str = field(metadata={"alias": "apiVersion"}, default=None)
    assignment_rule_id: str = field(metadata={"alias": "assignmentRuleId"}, default=None)
    number_records_failed: int = field(metadata={"alias": "numberRecordsFailed"}, default=None)
    total_processing_time: int = field(metadata={"alias": "totalProcessingTime"}, default=None)
    api_active_processing_time: int = field(metadata={"alias": "apiActiveProcessingTime"}, default=None)
    apex_processing_time: int = field(metadata={"alias": "apexProcessingTime"}, default=None)
    job_type: JobTypeEnum = field(metadata={"alias": "jobType"}, default=None)
    fast_path_enabled: bool = field(metadata={"alias": "fastPathEnabled"}, default=None)


@salesforce_api_dataclass
class BatchInfo:
    id: str = field(metadata={"alias": "id"}, default=None)
    job_id: str = field(metadata={"alias": "jobId"}, default=None)
    state: BatchStateEnum = field(metadata={"alias": "state"}, default=None)
    state_message: str = field(metadata={"alias": "stateMessage"}, default=None)
    created_date: datetime = field(metadata={"alias": "createdDate"}, default=None)
    system_modstamp: datetime = field(metadata={"alias": "systemModstamp"}, default=None)
    number_records_processed: int = field(metadata={"alias": "numberRecordsProcessed"}, default=None)
    number_records_failed: int = field(metadata={"alias": "numberRecordsFailed"}, default=None)
    total_processing_time: int = field(metadata={"alias": "totalProcessingTime"}, default=None)
    api_active_processing_time: int = field(metadata={"alias": "apiActiveProcessingTime"}, default=None)
    apex_processing_time: int = field(metadata={"alias": "apexProcessingTime"}, default=None)


@salesforce_api_dataclass
class BatchInfoList:
    batch_info: List[BatchInfo] = field(metadata={"alias": "batchInfo"}, default=None)


@salesforce_api_dataclass
class ResultError:
    fields: List[str] = field(metadata={"alias": "fields"}, default=None)
    message: str = field(metadata={"alias": "message"}, default=None)
    status_code: StatusCode = field(metadata={"alias": "statusCode"}, default=None)


@salesforce_api_dataclass
class sObject:
    type: str = field(metadata={"alias": "type"}, default=None)
    id: str = field(metadata={"alias": "Id"}, default=None)


@salesforce_api_dataclass
class QueryResult:
    records: List[sObject] = field(metadata={"alias": "records"}, default=None)


@salesforce_api_dataclass
class Result:
    errors: List[ResultError] = field(metadata={"alias": "errors"}, default=None)
    id: str = field(metadata={"alias": "id"}, default=None)
    success: bool = field(metadata={"alias": "success"}, default=None)
    created: bool = field(metadata={"alias": "created"}, default=None)


@salesforce_api_dataclass
class BatchResult:
    result: List[Result] = field(metadata={"alias": "result"}, default=None)


@salesforce_api_dataclass
class JobInfoList:
    job_info: List[JobInfo] = field(metadata={"alias": "jobInfo"}, default=None)

